version: '3.7'

services:

  sonic:
    image: valeriansaliou/sonic:v1.3.0
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    ports:
      - 1491:1491

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    entrypoint: /start-reload.sh  # live reload for development
    volumes: 
      - './backend/src:/app'
    ports:
      - 8000:80
    links:
      - "sonic:sonichost"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - "backend:backendhost"
